[package]
name = "icx-wasm"
version = "0.1.0"
authors = ["DFINITY Stiftung"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.34"
clap = { version = "3.0.14", features = ["derive", "cargo"] }
ic-wasm = { path = "../ic-wasm" }
walrus = "0.19.0"
